project:
  type: book
  output-dir: docs

book:
  title: An example report
  subtitle: The subtitle
#  cover-image: images/logo.png
#  image: images/logo.png
  downloads: [pdf, docx]
  author:
    - name: Jane Doe
      affiliations:
        - name: NOAA Fisheres
          department: Northwest Fisheries Science Center
    - name: Eva Nováková
      affiliations:
        - name: NOAA Fisheries
          department: West Coast Regional Office
    - name: Matti Meikäläinen
      affiliations:
        - name: NOAA Fisheries
          department: Southwest Fisheries Science Center
  chapters:
    - index.qmd
#    - text/CRchum.qmd
    - text/ICSRFchinook.qmd
    - text/ICUCchinook.qmd
    - text/LCchinook.qmd
    - text/UWchinook.qmd
    - text/ICSRsthd.qmd   
    - text/ICUCsthd.qmd
#    - text/LCcoho.qmd    
#    - text/LCsthd.qmd
#    - text/OCcoho.qmd     
#    - text/HCchum.qmd
    - text/UWsthd.qmd
    - text/conclusion.qmd
    - references.qmd

  site-url: https://nmfs-opensci.github.io/QuartoReport/
  repo-url: https://github.com/nmfs-opensci/QuartoReport
  repo-actions: [edit, source, issue]
  search: true

bibliography: [references.bib, SEDAR.bib]

execute:
  echo: false
  code-overflow: wrap

format:
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  pdf:
    documentclass: scrbook
    classoption: ["oneside"]
    template-partials: ["partials/before-body.tex"]
    toc: true
    toc-depth: 2
    lof: true
    lot: true
    include-in-header: 
      - partials/inheader.tex
